### ISSUE TITLE
Add .jshintrc

### ISSUE THREAD

**Issue by jsantell** [sole/arewedubstepyet.com#1]
Gulp file uses this but looks like it's not in the repository

**Comment by sole** [comment]
Does it? I didn't tell it to use it-just to use jshint o_o do you get an error or something?

**Comment by jsantell** [comment]
First time (embarrassingly) using gulp, so I just ran `gulp` in the working directory and get this:

```
[10:04:52] Using gulpfile ~/Dev/arewedubstepyet.com/gulpfile.js
[10:04:52] Starting 'lint'...
[10:04:52] Starting 'build-js'...
gulp.env has been deprecated. Use your own CLI parser instead. We recommend using yargs or minimist.
[10:04:52] Starting 'build-html'...
[10:04:52] Starting 'build-css'...
[10:04:52] Starting 'build-data'...
[10:04:52] Starting 'watch'...
[10:04:52] Finished 'watch' after 19 ms
[10:04:52] Finished 'build-css' after 62 ms
ERROR: Can't parse config file: /Users/jsantell/.jshintrc
```

Looks like it doesn't find `.jshintrc` in my fork directory, and keeps going up until it hits my home directory, not finding it all, so looks like the gulp-jshint module by default [looks up a .jshintrc](https://github.com/spenceralger/gulp-jshint#options), so maybe this should be disabled or the repo itself should have a .jshintrc, which would fix this I think

**Comment by sole** [comment]
Can you try if this commit https://github.com/sole/arewedubstepyet.com/commit/7c7e6cd67f1fb9fde374995412b29f866e7dd129 fixed your issue? (maybe I made it worse but I can't find the jshintrc in my path or anything for the life of me, yet this still lints!)

**Comment by jsantell** [comment]
Yup that fixes it for me! Looking into it more, I _did_ have a `~/.jshintrc` file, but it was when I was experimenting with some fixes for the vim plugin, so my jshintrc file is invalid.. hence "can't parse config file".. maybe have the jshintrc file in the repo itself if there are consistent lint rules? Guessing it didn't find a jshintrc config successfully for you, so skipped it, and found my broken one, and threw an error, but if there's a gulp lint build step, it might make sense to have a jshintrc in there, so our jshintrc's (theoretically!) would not conflict

**Comment by sole** [comment]
Alright I added a bit of jshintrc in here :D

**Comment by jsantell** [comment]
:metal:
